sudo: required

services:
 - docker

before_install:
  - docker build -t rubytong/react -f Dockerfile.dev .

script:
  - docker run rubytong/react npm run test -- --version

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reactapp"
  evn: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-087214725511"
  bucket_path: "docker-reactapp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"